config/routes.rb
Rails.application.routes.draw do
  root to: 'plans#index'
  resources :plans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  validates :title, :start_date, :end_date, presence: true
  validates :title, length: { maximum: 20 }
  validates :memo,  length: { maximum: 500 }
  validate :start_end_check, 

  def start_end_check
    if self.end_date && self.start_date && self.end_date < self.start_date
      errors.add(:end_date, "は開始日より前の日付で登録できません。")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(post_params)
    if @plan.save
      flash[:success] = "プランを登録しました"
      redirect_to plans_path
    else
      render "new"
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update(post_params)
      flash[:info] = "ユーザー#{@plan.id}が内容を変更しました"
      redirect_to plan_path(@plan)
    else
      render "edit"
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    flash[:info] = "ユーザーを削除しました"
    redirect_to plans_path
  end

  private

  def post_params
    params.require(:plan).permit(:title, :start_date, :end_date, :checkbox, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/css/bootstrap-material-datetimepicker.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/ja.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/js/bootstrap-material-datetimepicker.min.js"></script>
    

  <script>
    $(function(){
    $(".calendar").bootstrapMaterialDatePicker({
    weekStart:0,
    lang: "ja",
    time: false,
    format:"YYYY/MM/DD",
    minDate:moment()
  });
  });
  </script>
  </head>
  
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <span class="navbar-brand md-0 h1">スケジュール管理</span>
  </div>
</nav>
<div class="container">
  <% flash.each do |flash_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{flash_type}") %>
  <% end %>
  <%= yield %>
</div>
<script>
$(".delete-button").on("click", {
    const planId = $(this).attr('id');
    const url = 'http://localhost:3000/plans/${planId}';
    let link = document.getElementById('link');
    link.setAttribute('href', url);
  });
</script>
</body>
</html>

app/views/plans/edit.html.erb
<p class="fs-1">予定編集</p>
<%= render 'shared/form' %>

app/views/plans/index.html.erb
<p class="fs-1">予定一覧</p>

<%= link_to "新規作成", new_plan_path, class: 'btn btn-outline-primary', data: {"turbolinks" => false} %>

<table class="table table-dark table-striped text-center">
<thead>
  <tr>
    <th>ID</th>
    <th>タイトル</th>
    <th>開始日</th>
    <th>終了日</th>
    <th>終日</th>
    <th>更新日時</th>
  </tr>
</thead>
<tbody>
  <tr>
  <% @plans.each do |plan| %>
  <td><%= plan.id %></td>
  <td><%= plan.title %></td>
  <td><%= plan.start_date.strftime("%Y/%m/%d") %></td>
  <td><%= plan.end_date.strftime("%Y/%m/%d") %></td>
  <td><%= plan.checkbox ? '○' : ' ' %></td>
  <td><%= plan.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
  <td><%= link_to "詳細", plan_path(plan), class: 'btn btn-outline-primary' %></td>
  <td><%= link_to "編集", edit_plan_path(plan), class: 'btn btn-outline-primary', data: {"turbolinks" => false} %></td>
  <td><a href="" class='btn btn-outline-primary', id: "delete-botton", data-bs-toggle="modal", data-bs-target="#staticBackdrop-<%= plan.id %>">削除</a></td>

</tbody>

<!-- Modal -->

<div class="modal fade" id="staticBackdrop-<%= plan.id %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h5 class="modal-title" id="staticBackdropLabel">プラン削除画面</h5>
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
  </div>
  <div class="modal-body">
    本当に削除しますか??
  </div>
  <div class="modal-footer">
    <%= link_to "削除", plan_path(plan), method: :delete, class: 'btn btn-outline-primary', id: 'link' %>
    <%= link_to "キャンセル", plans_path, class: 'btn btn-outline-secondary' %>
  </div>
  </div>
  </div>
</div>
<% end %>
</table>
<div class="card">
  <div class="card-body">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">予定合計: <%= @plans.count %>件</li>
    <li class="list-group-item">本日の日付: <%= Time.current.strftime('%Y/%m/%d') %></li>
  </ul>
  </div>
</div>

app/views/plans/new.html.erb
<p class="fs-1">予定新規追加</p>
<%= render 'shared/form' %>

app/views/plans/show.html.erb
<nav class="navbar gray">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">タイトル: <%= @plan.title %></p></span>
  </div>
</nav>
<table class="table table-dark table-striped">
  <tr>
    <th>開始日</th>
    <td><%= @plan.start_date %></td>
  <tr>

  <tr>
    <th>終了日</th>
    <td><%= @plan.end_date %></td>
  </tr>

  <tr>
    <th>終日</th>
    <td><%= @plan.checkbox ? '○' : ' ' %></td>
  </tr>

  <tr>
    <th>スケジュールメモ</th>
    <td><%= @plan.memo %>
  </tr>
</table>
<div>
  <%= link_to "編集する", edit_plan_path(@plan), class: 'btn btn-outline-primary', data: {"turbolinks" => false} %>
  <%= link_to "戻る", plans_path,  class: 'btn btn-outline-secondary' %>
</div>

app/views/shared/_error_messages.html.erb
<% if @plan.errors.any? %>
  <div id="error_explanation">
  <div class="alert alert-danger">
    <p><%= pluralize(@plan.errors.count, "error") %>が原因で保存出来ませんでした</p>
    <ul>
    <% @plan.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  </div>
<% end %>  

app/views/shared/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_with model: @plan, local: true do |f| %>
    <%= render 'shared/error_messages' %>
    <p>
    <%= f.label :title, "タイトル" %>
    <%= f.text_field :title, class: 'form-control' %>
    </p>
    
    <p>
    <%= f.label :start_date, "開始日" %>
    <%= f.text_field :start_date, class: 'calendar form-control',  placeholder: '開始日' %>
    </p>

    <p>
    <%= f.label :end_date, "終了日" %>
    <%= f.text_field :end_date, class: 'calendar form-control', placeholder: '終了日' %>
    </p>
    
    <p>
    <%= f.check_box :checkbox, id: :plan_checkbox, :as => :boolean %>
    <%= f.label :checkbox, "終日の場合はチェックを入れます" %>
    </p>

    <p>
    <%= f.label :memo, "スケジュールメモ" %>
    <%= f.text_area :memo, class: 'form-control', rows: '5%' %>
    </p>

  <div>
    <%= f.submit "保存", class: 'btn btn-outline-primary' %>
    <%= link_to "キャンセル", plans_path, class: 'btn btn-outline-secondary' %>
  </div>
  </div>
</div>
<% end %>